from datetime import datetime, timedelta
import random

teams = ['A', 'B', 'C', 'D', 'E', 'F']

pt_teams = [
    "Sporting CP",
    "Benfica",
    "Porto",
    "Braga",
    "Vitória SC",
    "Moreirense",
    "Arouca",
    "Famalicão",
    "Casa Pia",
    "Farense"
]

#  all possible matches (both home and away)
valid_set = [[team1, team2] for team1 in teams for team2 in teams if team1 != team2]

valid_set_pt = [[team1, team2] for team1 in pt_teams for team2 in pt_teams if team1 != team2]

# Number of games n*(n-1)
# 6 teams --> 30 games


# Define the start date and end date of the two-month period
#start_date = datetime(2024, 5, 1)  # May 1, 2024
#end_date = datetime(2024, 9, 30)   # September 30, 2024

start_date_pt = datetime(2024, 9, 1)  # May 1, 2024
end_date_pt = datetime(2025, 7, 30)   # September 30, 2024

# Initialize a list to store the game dates
#game_dates = []
game_dates_pt = []

# Define the days of the week for the games (, Saturday, Sunday)
#game_days = [5, 6]  # Saturday, Sunday
game_days_pt = [5, 6]

# Define the start time and end time for the games (in hours)
#start_time = 20  # 8:00 PM
start_time_pt = 20  # 8:00 PM


# Loop through the dates in the two-month period
current_date_pt = start_date_pt
while current_date_pt <= end_date_pt:
    # Check if the current date is a Friday, Saturday, or Sunday
    if current_date_pt.weekday() in game_days_pt:
        # Generate game times between start_time and end_time with 1-hour interval
        game_time_pt = datetime(current_date_pt.year, current_date_pt.month, current_date_pt.day, start_time_pt)
        game_dates_pt.append(game_time_pt)  # Adding the game time to game_dates
    # Move to the next day
    current_date_pt += timedelta(days=1)

# Randomly select 30 game dates
random_game_dates_pt = random.sample(game_dates_pt, (len(pt_teams)*(len(pt_teams)-1)))

# Order the games
random_game_dates_pt.sort()

# Print the list of game dates
for game_date_pt in random_game_dates_pt:
    print(game_date_pt)

print(len(random_game_dates_pt))

# Create a list with the dates generated by the previous code

random_game_dates = [
    datetime(2024, 5, 4, 20, 0),
    datetime(2024, 5, 5, 20, 0),
    datetime(2024, 5, 18, 20, 0),
    datetime(2024, 5, 19, 20, 0),
    datetime(2024, 5, 25, 20, 0),
    datetime(2024, 6, 1, 20, 0),
    datetime(2024, 6, 2, 20, 0),
    datetime(2024, 6, 8, 20, 0),
    datetime(2024, 6, 9, 20, 0),
    datetime(2024, 6, 15, 20, 0),
    datetime(2024, 6, 23, 20, 0),
    datetime(2024, 6, 29, 20, 0),
    datetime(2024, 6, 30, 20, 0),
    datetime(2024, 7, 6, 20, 0),
    datetime(2024, 7, 7, 20, 0),
    datetime(2024, 7, 13, 20, 0),
    datetime(2024, 7, 21, 20, 0),
    datetime(2024, 7, 27, 20, 0),
    datetime(2024, 7, 28, 20, 0),
    datetime(2024, 8, 4, 20, 0),
    datetime(2024, 8, 11, 20, 0),
    datetime(2024, 8, 17, 20, 0),
    datetime(2024, 8, 18, 20, 0),
    datetime(2024, 8, 24, 20, 0),
    datetime(2024, 8, 31, 20, 0),
    datetime(2024, 9, 1, 20, 0),
    datetime(2024, 9, 7, 20, 0),
    datetime(2024, 9, 8, 20, 0),
    datetime(2024, 9, 21, 20, 0),
    datetime(2024, 9, 28, 20, 0)
]

random_game_dates_pt = [
    datetime(2024, 9, 1, 20, 0),
    datetime(2024, 9, 7, 20, 0),
    datetime(2024, 9, 8, 20, 0),
    datetime(2024, 9, 14, 20, 0),
    datetime(2024, 9, 15, 20, 0),
    datetime(2024, 9, 21, 20, 0),
    datetime(2024, 9, 22, 20, 0),
    datetime(2024, 9, 28, 20, 0),
    datetime(2024, 9, 29, 20, 0),
    datetime(2024, 10, 5, 20, 0),
    datetime(2024, 10, 6, 20, 0),
    datetime(2024, 10, 12, 20, 0),
    datetime(2024, 10, 13, 20, 0),
    datetime(2024, 10, 19, 20, 0),
    datetime(2024, 10, 20, 20, 0),
    datetime(2024, 10, 26, 20, 0),
    datetime(2024, 10, 27, 20, 0),
    datetime(2024, 11, 2, 20, 0),
    datetime(2024, 11, 9, 20, 0),
    datetime(2024, 11, 10, 20, 0),
    datetime(2024, 11, 16, 20, 0),
    datetime(2024, 11, 17, 20, 0),
    datetime(2024, 11, 23, 20, 0),
    datetime(2024, 11, 24, 20, 0),
    datetime(2024, 11, 30, 20, 0),
    datetime(2024, 12, 7, 20, 0),
    datetime(2024, 12, 14, 20, 0),
    datetime(2024, 12, 15, 20, 0),
    datetime(2024, 12, 21, 20, 0),
    datetime(2024, 12, 22, 20, 0),
    datetime(2024, 12, 28, 20, 0),
    datetime(2024, 12, 29, 20, 0),
    datetime(2025, 1, 4, 20, 0),
    datetime(2025, 1, 5, 20, 0),
    datetime(2025, 1, 11, 20, 0),
    datetime(2025, 1, 12, 20, 0),
    datetime(2025, 1, 18, 20, 0),
    datetime(2025, 1, 19, 20, 0),
    datetime(2025, 1, 25, 20, 0),
    datetime(2025, 1, 26, 20, 0),
    datetime(2025, 2, 1, 20, 0),
    datetime(2025, 2, 2, 20, 0),
    datetime(2025, 2, 8, 20, 0),
    datetime(2025, 2, 9, 20, 0),
    datetime(2025, 2, 15, 20, 0),
    datetime(2025, 2, 16, 20, 0),
    datetime(2025, 2, 22, 20, 0),
    datetime(2025, 2, 23, 20, 0),
    datetime(2025, 3, 1, 20, 0),
    datetime(2025, 3, 2, 20, 0),
    datetime(2025, 3, 9, 20, 0),
    datetime(2025, 3, 15, 20, 0),
    datetime(2025, 3, 16, 20, 0),
    datetime(2025, 3, 22, 20, 0),
    datetime(2025, 3, 23, 20, 0),
    datetime(2025, 3, 29, 20, 0),
    datetime(2025, 3, 30, 20, 0),
    datetime(2025, 4, 5, 20, 0),
    datetime(2025, 4, 6, 20, 0),
    datetime(2025, 4, 12, 20, 0),
    datetime(2025, 4, 13, 20, 0),
    datetime(2025, 4, 19, 20, 0),
    datetime(2025, 4, 20, 20, 0),
    datetime(2025, 4, 26, 20, 0),
    datetime(2025, 4, 27, 20, 0),
    datetime(2025, 5, 3, 20, 0),
    datetime(2025, 5, 4, 20, 0),
    datetime(2025, 5, 10, 20, 0),
    datetime(2025, 5, 11, 20, 0),
    datetime(2025, 5, 17, 20, 0),
    datetime(2025, 5, 18, 20, 0),
    datetime(2025, 5, 24, 20, 0),
    datetime(2025, 5, 25, 20, 0),
    datetime(2025, 5, 31, 20, 0),
    datetime(2025, 6, 1, 20, 0),
    datetime(2025, 6, 7, 20, 0),
    datetime(2025, 6, 8, 20, 0),
    datetime(2025, 6, 14, 20, 0),
    datetime(2025, 6, 15, 20, 0),
    datetime(2025, 6, 21, 20, 0),
    datetime(2025, 6, 22, 20, 0),
    datetime(2025, 6, 28, 20, 0),
    datetime(2025, 6, 29, 20, 0),
    datetime(2025, 7, 5, 20, 0),
    datetime(2025, 7, 6, 20, 0),
    datetime(2025, 7, 12, 20, 0),
    datetime(2025, 7, 13, 20, 0),
    datetime(2025, 7, 19, 20, 0),
    datetime(2025, 7, 20, 20, 0),
    datetime(2025, 7, 27, 20, 0)
]
